
def folderName = 'generated-jobs'
def gitRepo = 'https://github.com/northbear/jenkins-generated-jobs.git'
def githubRepo = 'northbear/jenkins-generated-jobs'

folder('generated-jobs') {
    displayName('Generated Jobs')
    description('Folder for jobs generated by another jobs')
}    

pipelineJob("$folderName/build-flask-app") {
    definition {
        cpsScm {
            lightweight()
            scm {
                github(githubRepo, 'master')
            }
            scriptPath('docker-flask-builder/Jenkinsfile')
        }
    }
}

pipelineJob("$folderName/build-nginx-proxy") {
    definition {
        cpsScm {
            lightweight()
            scm {
                github(githubRepo, 'master')
            }
            scriptPath('docker-nginx-builder/Jenkinsfile')
        }
    }
}

pipelineJob("$folderName/run-application") {
    definition {
        cpsScm {
            lightweight()
            scm {
                github(githubRepo, 'master')
            }
            scriptPath('run-system/Jenkinsfile')
        }
    }
}

